export const cities = [
  {
    city: "Udaipur",
    url: "assets/hotels/oberoi_udaipur.jpg",
    latitude: 24.5774,
    longitude: 73.6724,
    state: "Rajasthan",
    title: "Udaipur Palace",
  },
  {
    city: "Hyderabad",
    url: "assets/hotels/TajKrishna_Hyderabad.jpg",
    latitude: 17.4164,
    longitude: 78.4497,
    state: "Telangana",
    title: "Hotel Taj krishna",
  },
  {
    city: "Anjuna",
    url: "assets/hotels/WestinGoa_Goa.jpg",
    latitude: 15.58896,
    longitude: 73.74349,
    state: "Goa",
    title: "The Westin Goa",
  },
  {
    city: "Kochi",
    url: "assets/hotels/sheraton_kochi.jpg",
    latitude: 10.029489,
    longitude: 76.307551,
    state: "Kerela",
    title: "Hotel Sheraton",
  },
  {
    city: "NewDelhi",
    url: "assets/hotels/roseate_newdelhi.jpg",
    latitude: 28.5508098991,
    longitude: 77.1205663638,
    state: "New Delhi",
    title: "Roseate",
  },
  {
    city: "Jaipur",
    url: "assets/hotels/Rambagh-jaipur.jpg",
    latitude: 26.8981,
    longitude: 75.8081,
    state: "Rajasthan",
    title: "Rambagh Palace",
  },
  {
    city: "Guwahati",
    url: "assets/hotels/vivanta_Guwahati.jpg",
    latitude: 26.12522,
    longitude: 91.8174,
    state: "Assam",
    title: "vivanta",
  },
  {
    city: "Kolkata",
    url: "assets/hotels/oberoi_kolkata.jpg",
    latitude: 22.5617,
    longitude: 88.3513,
    state: "West Bengal",
    title: "Oberoi kolkata",
  },
  {
    city: "Bengaluru",
    url: "assets/hotels/jw-marriott-hotel-bengaluru.jpg",
    latitude: 12.979,
    longitude: 77.7284,
    state: "Karnataka",
    title: "Hotel Marriot",
  },
];
